### ISSUE TITLE
module 'torchtext' has no attribute 'vocab'

### ISSUE THREAD

**Issue by LensGrinder4E00** [BeachWang/DAIL-SQL#37]
在我运行python data_preprocess.py命令时，得到了如下报错：

Traceback (most recent call last):
  File "data_preprocess.py", line 131, in <module>
    schema_linking_producer(spider_dev, spider_train, spider_table, spider_db, spider_dir)
  File "data_preprocess.py", line 35, in schema_linking_producer
    word_emb = GloVe(kind='42B', lemmatize=True)
  File "/Users/minstrel./PythonProjects/DAIL-SQL-main/utils/pretrained_embeddings.py", line 46, in __init__
    self.glove = torchtext.vocab.GloVe(name=kind, cache=cache)
AttributeError: module 'torchtext' has no attribute 'vocab'

请问要怎么解决？

**Comment by Zqzqsb** [comment]
pip3 uninstall torchtext
pip3 install torchtext==0.17.0 --no-cache-dir

**Comment by Ptah4E00** [comment]
> pip3 uninstall torchtext pip3 install torchtext==0.17.0 --no-cache-dir

Thanks！It's solved, you're so helpful！
