### ISSUE TITLE
为什么在data_process报错AttributeError: module 'corenlp' has no attribute 'CoreNLPClient'

### ISSUE THREAD

**Issue by miokiko** [BeachWang/DAIL-SQL#50]
Traceback (most recent call last):
  File "data_preprocess.py", line 131, in <module>
    schema_linking_producer(spider_dev, spider_train, spider_table, spider_db, spider_dir)
  File "data_preprocess.py", line 52, in schema_linking_producer
    linking_processor.add_item(item, schema, section, validation_info)
  File "D:\text2sql\DAIL-SQL-main\utils\linking_process.py", line 143, in add_item
    preprocessed = self.preprocess_item(item, schema, validation_info)
  File "D:\text2sql\DAIL-SQL-main\utils\linking_process.py", line 150, in preprocess_item
    question, question_for_copying = self._tokenize_for_copying(item['question_toks'], item['question'])
  File "D:\text2sql\DAIL-SQL-main\utils\linking_process.py", line 195, in _tokenize_for_copying
    return self.word_emb.tokenize_for_copying(unsplit)
  File "D:\text2sql\DAIL-SQL-main\utils\pretrained_embeddings.py", line 64, in tokenize_for_copying
    ann = corenlp.annotate(text, self.corenlp_annotators)
  File "D:\text2sql\DAIL-SQL-main\utils\linking_utils\corenlp.py", line 67, in annotate
    _singleton = CoreNLP()
  File "D:\text2sql\DAIL-SQL-main\utils\linking_utils\corenlp.py", line 42, in __init__
    self.client = corenlp.CoreNLPClient()
AttributeError: module 'corenlp' has no attribute 'CoreNLPClient'

**Comment by BeachWang** [comment]
这可能是corenlp的版本问题，请参考这个[issue](https://github.com/microsoft/rat-sql/issues/54)。
